# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mean_rice_R <- function(nu, sigma) {
    .Call(`_symR_mean_rice_R`, nu, sigma)
}

J <- function(n) {
    .Call(`_symR_J`, n)
}

eigenvals_J <- function(n) {
    .Call(`_symR_eigenvals_J`, n)
}

Bloch_eqn_R <- function(W_row, TE, TR) {
    .Call(`_symR_Bloch_eqn_R`, W_row, TE, TR)
}

v_mat_R <- function(W, TE, TR) {
    .Call(`_symR_v_mat_R`, W, TE, TR)
}

Generate_r <- function(W, TE, TR, sigma) {
    .Call(`_symR_Generate_r`, W, TE, TR, sigma)
}

dee_v_ij_dee_W_ik <- function(W_row, TE, TR, j, k) {
    .Call(`_symR_dee_v_ij_dee_W_ik`, W_row, TE, TR, j, k)
}

dee_2_v_ij_dee_W_ik_dee_W_ik1 <- function(W_row, TE, TR, j, k, k1) {
    .Call(`_symR_dee_2_v_ij_dee_W_ik_dee_W_ik1`, W_row, TE, TR, j, k, k1)
}

Init_val_least_sq_R <- function(train, TE_train, TR_train, our_dim_1, train_scale, TE_scale, TR_scale, maxiter_LS, W_1_init, W_2_init) {
    .Call(`_symR_Init_val_least_sq_R`, train, TE_train, TR_train, our_dim_1, train_scale, TE_scale, TR_scale, maxiter_LS, W_1_init, W_2_init)
}

AECM_R <- function(W, our_dim_1, TE_train, TR_train, sigma_train, train, train_scale, TE_scale, TR_scale, black_list, maxiter = 50L, penalized = 1L, abs_diff = 1e-1, rel_diff = 1e-5, verbose = 0L, verbose2 = 0L) {
    .Call(`_symR_AECM_R`, W, our_dim_1, TE_train, TR_train, sigma_train, train, train_scale, TE_scale, TR_scale, black_list, maxiter, penalized, abs_diff, rel_diff, verbose, verbose2)
}

Var_contrast <- function(W, Psi_inv, beta, contrast, our_dim_1, TE_train, TR_train, sigma_train, train, TE_test, TR_test, sigma_test, test, train_scale, TE_scale, TR_scale, black_list, cg_maxiter = 50L, cg_tol = 1e-6, penalized = 1L, abs_diff = 1e-1, rel_diff = 1e-5, verbose = 0L, verbose2 = 0L) {
    .Call(`_symR_Var_contrast`, W, Psi_inv, beta, contrast, our_dim_1, TE_train, TR_train, sigma_train, train, TE_test, TR_test, sigma_test, test, train_scale, TE_scale, TR_scale, black_list, cg_maxiter, cg_tol, penalized, abs_diff, rel_diff, verbose, verbose2)
}

Var_contrast_boot <- function(W, Psi_inv, beta, contrast, our_dim_1, TE_train, TR_train, sigma_train, train, TE_test, TR_test, sigma_test, test, train_scale, TE_scale, TR_scale, black_list, B = 15L, EM_iter = 10L, abs_diff = 1e-1, rel_diff = 1e-4, penalized = 1L) {
    .Call(`_symR_Var_contrast_boot`, W, Psi_inv, beta, contrast, our_dim_1, TE_train, TR_train, sigma_train, train, TE_test, TR_test, sigma_test, test, train_scale, TE_scale, TR_scale, black_list, B, EM_iter, abs_diff, rel_diff, penalized)
}

OSL_R <- function(W, our_dim_1, TE_train, TR_train, sigma_train, train, train_scale, TE_scale, TR_scale, black_list, maxiter = 50L, penalized = 1L, abs_diff = 1e-1, rel_diff = 1e-5, verbose = 0L, verbose2 = 0L) {
    .Call(`_symR_OSL_R`, W, our_dim_1, TE_train, TR_train, sigma_train, train, train_scale, TE_scale, TR_scale, black_list, maxiter, penalized, abs_diff, rel_diff, verbose, verbose2)
}

Performance_test_R <- function(W, test, TE_test, TR_test, sigma_test, black_list, v_type = 1L, measure_type = 1L, scale = 1L, verbose = 0L) {
    .Call(`_symR_Performance_test_R`, W, test, TE_test, TR_test, sigma_test, black_list, v_type, measure_type, scale, verbose)
}

AECM_R_3D <- function(W, our_dim_1, TE_train, TR_train, sigma_train, train, train_scale, TE_scale, TR_scale, black_list, maxiter = 50L, penalized = 1L, abs_diff = 1e-1, rel_diff = 1e-5, verbose = 0L, verbose2 = 0L) {
    .Call(`_symR_AECM_R_3D`, W, our_dim_1, TE_train, TR_train, sigma_train, train, train_scale, TE_scale, TR_scale, black_list, maxiter, penalized, abs_diff, rel_diff, verbose, verbose2)
}

OSL_R_3D <- function(W, our_dim_1, TE_train, TR_train, sigma_train, train, train_scale, TE_scale, TR_scale, black_list, maxiter = 50L, penalized = 1L, abs_diff = 1e-1, rel_diff = 1e-5, verbose = 0L, verbose2 = 0L) {
    .Call(`_symR_OSL_R_3D`, W, our_dim_1, TE_train, TR_train, sigma_train, train, train_scale, TE_scale, TR_scale, black_list, maxiter, penalized, abs_diff, rel_diff, verbose, verbose2)
}

